### ISSUE TITLE
Hardcoded assumption of a browser environment

### ISSUE THREAD

**Issue by tusharsrivastava** [anywhichway/benchtest#4]
https://github.com/anywhichway/benchtest/blob/24bbb75964e278c49bc119bee43152ec4e596207/index.js#L130

The code snippet above which fails #3 is due to an assumption that user is running `benchtest` in a browser environment which may not be true in every scenario (for example, while running test suite in CLI).

This needs to be corrected

**Comment by anywhichway** [comment]
On January 1st of this year, in something of a "Forest Gump" moment, I ceased writing code. I will take pull requests or transfer the repository to another person. However, I will not be fixing.

I will update the repository description to say this.

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Tushar Srivastava ***@***.***>
Sent: Sunday, March 28, 2021 8:50:11 AM
To: anywhichway/benchtest ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anywhichway/benchtest] Hardcoded assumption of a browser environment (#4)


https://github.com/anywhichway/benchtest/blob/24bbb75964e278c49bc119bee43152ec4e596207/index.js#L130

The code snippet above which fails #3<https://github.com/anywhichway/benchtest/issues/3> is due to an assumption that user is running benchtest in a browser environment which may not be true in every scenario (for example, while running test suite in CLI).

This needs to be corrected

**Comment by tusharsrivastava** [comment]
I hope you'll have much more fun in a non-coding environment. Best of luck

**Comment by evisong** [comment]
Best wishes to @anywhichway.

For anyone who runs into this issue when running in Node, you may workaround it by adding a 

```js
global.document = {getElementById: () => undefined};
```

to your `before()` block.
